name: deploy

on:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive forge-std solmate openzeppelin-contracts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot
  deploy-to-polygon:
    needs: check
    steps:
      - run:
          - |
            forge script script/Disperse.s.sol:DisperseScript 
            --rpc-url https://polygon-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_EVM_POLYGON_KEY }}
            --broadcast 
            --verify 
            --etherscan-api-key ${{ secrets.ETH_SCAN_API_KEY }}
