name: deploy-to-avalanche

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  SNOW_TRACE_KEY: ${{ secrets.SNOW_TRACE_KEY }}

on:
  workflow_run:
    workflows:
      - deploy
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    name: deploy-to-avalanche
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive forge-std solmate openzeppelin-contracts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run install
        run: forge install

      - name: Deploy to avalanche
        run: forge script script/Disperse.s.sol:DisperseScript --rpc-url avalanche --broadcast --verify --etherscan-api-key avalanche
