name: deploy-to-optimism

env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ALCHEMY_EVM_OPTIMISM_API_KEY: ${{ secrets.ALCHEMY_EVM_OPTIMISM_API_KEY }}
  OP_SCAN_KEY: ${{ secrets.OP_SCAN_KEY }}

on:
  workflow_run:
    workflows:
      - deploy
    types:
      - completed
  workflow_dispatch:

jobs:
  check:
    name: deploy-to-optimism
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive forge-std solmate openzeppelin-contracts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run install
        run: forge install

      - name: Deploy to optimism
        run: forge script script/Disperse.s.sol:DisperseScript --rpc-url optimism --broadcast --verify --etherscan-api-key optimism
